[package]
name = "remux-web"
version = "0.1.0"
authors = ["lostb1t <coding-mosses0z@icloud.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daisy_rsx = "0.1.14"
dioxus = { version = "0.6.2", features = ["router"] }
dioxus-logger = "0.6.2"
eyre = "0.6.12"
reqwest = { version = "0.12.9", features = ["json"] }
serde = "1.0.216"
serde_json = "1.0.137"
strum = "0.26.3"
strum_macros = "0.26.4"
getrandom = { version = "0.2.15", features = ["js"] }
dyn-clone = "1.0.18"
async-trait = "0.1.86"
tokio = { version = "1.43", features = ["io-util", "time"] }
tokio_with_wasm = { version = "0.7.4", features = ["time"] }
dioxus-motion = { version = "0.3.1", optional = true, default-features = false }
proc-macro2 = "1.0.93"
dioxus-components = "0.0.0"
serde_derive = "1.0.219"


# [patch.crates-io]
# # rand = { version = "0.9" }
# # rand = "0.9"
# # getrandom = { version = "0.3", features = ["wasm_js"] }
# getrandom = { version = "0.2.15", features = ["js"] }

[features]
default = ["web"]
web = ["dioxus/web", "dioxus-motion/web", "dioxus-motion/transitions"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
