[tasks.serve-web]
env = { "RUSTFLAGS" = "--cfg getrandom_backend=\"wasm_js\"" }
command = "dx"
args = ["serve", "--platform", "web", "--port", "4000"]

[tasks.watch-tailwind]
command = "npx"
args = ["tailwindcss", "-i", "./input.css", "-o", "./assets/tailwind.css", "--watch"]
#watch = true

[tasks.dev]
run_task = { name = ["watch-tailwind", "serve-web"], fork = true, parallel = true }