[env]
RUST_LOG = "info,axum=info,tower_http=info,remux_server=debug,hyper=warn,sqlx=error"
RUST_BACKTRACE = 0
CONFIG = "./config"
AXUM_ANYHOW_EXPOSE_ERRORS=1
# HTTP_PROXY="http://10.0.10.11:9090"
# HTTPS_PROXY="http://10.0.10.11:9090"
DATABASE_URL = "sqlite://db.sqlite"
WEB_PATH = "../jellyfin-web/dist"
DB="db.sqlite"

[env.test]
DATABASE_URL = "sqlite://test.sqlite"
DB="test.sqlite"

[tasks.db-create]
command = "cargo"
args = ["sqlx", "database", "create"]

[tasks.db-prepare]
command = "cargo"
args = ["sqlx", "prepare"]

[tasks.db-migrate]
command = "cargo"
args = ["sqlx", "migrate", "run", "--source", "./migrations"]

[tasks.db-remove]
command = "rm"
args = ["-f", "${DB}"]

[tasks.db-reset]
dependencies = ["db-remove", "db-create", "db-migrate"]

[tasks.test]
#env = { "DATABASE_URL" = "sqlite://test.sqlite" }
dependencies = ["db-reset"]
command = "cargo"
args = ["test"]

[tasks.dev]
command = "cargo"
args = ["run"]
watch = true

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.build-docker]
command = "docker"
args = ["buildx", "build", "-f", "docker/Dockerfile.dev",  "--platform", "linux/arm64", "-t", "ghcr.io/lostb1t/remux-server:local", "."]

[tasks.build]
command = "docker"
args = ["build", "-f", "Dockerfile.dev", "-t", "remux-dev", "."]

[tasks.dev-container]
command = "docker"
args = ["run", "--rm", "-it", "-p", "8080:8080", "-v", "${PWD}:/app", "-v", "target:/app/target", "remux-dev"]
dependencies = ["build-dev"]
