[tasks.serve-web]
#env = { "RUSTFLAGS" = "--cfg getrandom_backend=\"wasm_js\"" }
command = "dx"
# args = ["serve", "--platform", "web", "--port", "4000", "--addr", "0.0.0.0"]
args = ["serve", "--platform", "web", "--port", "4000", "--addr", "0.0.0.0", "--hot-reload", "true"]

[tasks.watch-tailwind]
command = "sh"
args = ["-c", "npx tailwindcss -i ./input.css -o ./assets/tailwind.css --watch > /dev/null 2>&1"]
#watch = true

[tasks.dev]
run_task = { name = ["watch-tailwind", "serve-web"], fork = true, parallel = true }
# run_task = { name = ["watch-tailwind", "serve-web"], parallel = true }

[tasks.build-web]
command = "dx"
args = ["build", "--platform", "web", "--release"]

[tasks.build-image]
command = "docker"
args = ["buildx", "build", "-t", "ghcr.io/lostb1t/remux:latest", ".", "--load"]

[tasks.sync]
command = "sh"
args = ["-c", "while true; do rsync -avz --delete kenobi:/root/Projects/remux-web/src/ /Users/sarendsen/Projects/remux/src/; sleep 2; done"]

[tasks.fmt]
script = [
  "cargo fmt",
  "dx fmt"
]

[tasks.deploy]
dependencies = ["build-web"]
script = [
  "rm -rf ./docs/",
  "mv ./target/dx/remux/release/web/public/ ./docs/",
  "git add ./docs",
	"git commit -m \"Update docs\"",
	"git push origin main"
]

[tasks.push]
dependencies = ["fmt"]
script = [
	"git commit -am \"wip\"",
	"git push origin main"
]