#!/usr/bin/env bash

# We'll do some cursed filtering to the API spec before handing it to
# progenitor. TODO: actually fix this stuff!

# Remove endpoints, they can't be generated by progenitor atm
filter_paths='del(.components.schemas.TranscodingInfo.properties.TranscodeReasons.enum)'
#filter_paths='del(.components.schemas.TranscodingInfo.properties.TranscodeReasons)'
# Remove enum array when a property already validates against a subschema
# (progenitor doesn't like it)
filter_enums='
.components.schemas |= (
	with_entries(
		.value |= (
			if has("properties") then
				.properties |= (
					with_entries(
						.value |= (
							if has("enum") and has("allOf") then
								del(.enum)
							else
								.
							end
						)
					)
				)
			else
				.
			end
		)
	)
)
'

filter_multiple_bodies='walk(if type == "object" and has("requestBody") and (.requestBody.content | length) > 1 then .requestBody.content |= {"application/json": .["application/json"]} else . end)'
filter_unsupported_bodies='walk(if type == "object" and .requestBody?.content?["text/plain"]?.schema?.format == "binary" then del(.requestBody) else . end)'
filter_media_wildcard='walk(
  if type == "object" and .requestBody.content?["image/*"]? then
    .requestBody.content["application/octet-stream"] = .requestBody.content["image/*"] | del(.requestBody.content["image/*"])
  else
    .
  end
)'
filter_multiple_responses='walk(if type == "object" and has("responses") and (.responses | length) > 1 then .responses |= { (keys_unsorted[0]): .[keys_unsorted[0]] } else . end)'
#filter_media_wildcard='walk(
#  if type == "object" and .post.requestBody.content?["image/*"]? then
#    del(.post)
#  else
#    .
#  end
#)'

curl -s https://api.jellyfin.org/openapi/jellyfin-openapi-stable.json |
	jq "$filter_paths | $filter_enums | $filter_multiple_bodies | $filter_unsupported_bodies | $filter_media_wildcard | $filter_multiple_responses" > jellyfin-openapi-stable.json

RUST_LOG=debug cargo progenitor \
	-i jellyfin-openapi-stable.json \
	-o jellyfin_api \
	-n jellyfin_api \
	-v 10.9.2 \
	--interface builder \
	--license-name Unlicense

#rm jellyfin-openapi-stable.json

# RED='\033[1;31m'
# printf "${RED}Remember to fix Cargo.toml and bump version number\n"