name: Build Dioxus Desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos
            runner: macos-14
            target: aarch64-apple-darwin
          - os: linux
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows
            runner: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo

      - name: Install Dioxus CLI (only if needed)
        run: |
          if ! command -v dx >/dev/null || ! dx --version | grep -q "0.7.0-alpha.3"; then
            cargo install --force dioxus-cli@0.7.0-alpha.3
          fi
      - name: Install dependencies (Linux only)
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libxdo-dev

      - name: Build Dioxus desktop app
        run: dx bundle --release --platform desktop || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: remux-${{ matrix.os }}
          path: ⁨target⁩/dx⁩/remux⁩/release/bundle⁩