name: Build Dioxus Desktop (Linux)

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Build with dx for ${{ matrix.target }}
        run: dx build --platform desktop --release --target ${{ matrix.target }}

      - name: Upload binary 
        uses: actions/upload-artifact@v4
        with:
          name: remux-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/remux