name: Build Mobile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
         # - os: macos
         #   runner: macos-14
         #   target: aarch64-apple-darwin
          - os: linux
            runner: ubuntu-latest
            platform: android
            target: aarch64-linux-android
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: aarch64-linux-android

      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform }}

      - name: Install cargo-binstall
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pwsh -Command "Set-ExecutionPolicy Unrestricted -Scope Process; iex (iwr 'https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.ps1').Content"
          else
            curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          fi

      - name: Install Dioxus CLI
        run: |
          cargo binstall --force --no-confirm dioxus-cli@0.7.0-alpha.3

      - name: Build app
        run: |
          dx bundle --platform ${{ matrix.platform }} --trace --target ${{ matrix.target }}
      
      - name: Prepare artifact (Android)
        if: matrix.os == 'linux'
        run: |
          mkdir -p artifacts
          cp target/dx/remux/release/android/app/*.* artifacts/
          cp dist/*.* artifacts/
      
      - name: Prepare artifact (macOS)
        if: matrix.os == 'macos'
        run: |
          mkdir -p artifacts
          cp dist/Remux_0.0.0_aarch64.dmg artifacts/remux-macos.dmg

      - name: Upload platform artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-package
          path: artifacts/*

  release:
    name: Upload to GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
          merge-multiple: true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build
          prerelease: true
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}